logging:
  level:
    io.lettuce.core: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  redis:
    sentinel:
      master: # master节点名称
      nodes:
        # - 192.168.230.101:6379 #哨兵节点1..2..3...
